# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('datetime_filed', models.DateTimeField()),
                ('attending_op', models.CharField(max_length=100)),
                ('is_job_reworked', models.BooleanField(default=False)),
                ('post_is_job_reworked', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
